// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEfztd1Pao1XWzbThQ2F7dZoD-n5W5yq8',
    appId: '1:20846053862:web:c0b9e5582fdae99ad5ee27',
    messagingSenderId: '20846053862',
    projectId: 'taxi-4-hire',
    authDomain: 'taxi-4-hire.firebaseapp.com',
    storageBucket: 'taxi-4-hire.appspot.com',
    measurementId: 'G-7021YCSRMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvhw3ufCXLPwfR8kt_VQ41vWPEvUMyKfs',
    appId: '1:20846053862:android:e1ff68f7087750e9d5ee27',
    messagingSenderId: '20846053862',
    projectId: 'taxi-4-hire',
    storageBucket: 'taxi-4-hire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL2OPLSWGYpl0rypiwXWbVYVqzucFCj4Q',
    appId: '1:20846053862:ios:8448c0ee4d6a5752d5ee27',
    messagingSenderId: '20846053862',
    projectId: 'taxi-4-hire',
    storageBucket: 'taxi-4-hire.appspot.com',
    iosClientId: '20846053862-58b6q4cblo7hcu7h20m5qsavk0vb50ub.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxi4hire',
  );
}
